name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  lint:
    name: Lint, format and type checking
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  publish:
    runs-on: ubuntu-latest
    needs: lint

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
